01 install solidus without frontend (#1)
* Install Solidus 3.2.4 gem

```shell
bundle add solidus
```

* Install Solidus without migrations

```shell
bin/rails g solidus:install --migrate=false --sample=false --seed=false
```

We only added `solidus_auth_devise` when asked. (this is the default authentication).

The other questions we set to `none`. So no default payment:

```shell
Please select a payment method name: [paypal, bolt, none] (paypal) none
```

and no frontend installation, we will do the frontend in a later step.

```shell
Which frontend would you like to use? solidus_starter_frontend is
recommended. However, some extensions are still only compatible with
the now deprecated solidus_frontend.

[solidus_starter_frontend, solidus_frontend, none] (solidus_starter_frontend) none
```

The `solidus_started_frontend` will not be able to install in this setup, it assumes
a barebone Rails setup and we made some choices here :)

* Run StrongMigrations checks after install

Since we are using the [Strong Migrations](https://github.com/ankane/strong_migrations) gem
and because of that if we would run the migrations automatically it will break.
We installed Solidus without running the migrations (and some of the other steps that need the migrations) and
configure Strong Migrations to start checking after the installed migrations.

* Run standardRb fix over all generated code

* Run the migrations

```shell
bin/rails db:migrate
```

I had to run `bin/rails db:schema:dump` as well to generate the
new `db/schema.rb`.

* Set css_compressor to nil

We use esbuild with jsbundling and cssbundling and Solidus adds
sass since that's needed for solidus_backend. Setting the css_compressor
to nil solves this error:

Failure/Error: Unable to find stdin to read failed line

     ActionView::Template::Error:
       Error: Function rgb is missing argument $green.
               on line 1070 of stdin
       >>   background-color: rgb(243 244 246 / var(--tw-bg-opacity));

          --------------------^