Set css_compressor to nil
We use esbuild with jsbundling and cssbundling and Solidus adds
sass since that's needed for solidus_backend. Setting the css_compressor
to nil solves this error:

Failure/Error: Unable to find stdin to read failed line

     ActionView::Template::Error:
       Error: Function rgb is missing argument $green.
               on line 1070 of stdin
       >>   background-color: rgb(243 244 246 / var(--tw-bg-opacity));

          --------------------^